---
title: "detenion-liberation-data-clean"
author: "Meet Muchhala"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(tidyverse)
library(here)
library(sf)
library(dplyr)
library(tmap)

```

```{r}

## Loading the EJScren raw data
ejscreen_data_raw <- read_sf(here("data", "ejscreen_2023.gdb")) %>% 
  clean_names()

## Selecting relevant percentiles variables for pollution and demographics as found in EJScreen Data Dictionary

ejscreen_sf <- ejscreen_data_raw %>% 
  clean_names() %>% 
  select(id, p_pnpl, p_prmp, p_ptsdf, p_ozone, p_dslpm, p_cancer, p_resp, p_rsei_air, exceed_count_80, arealand, areawater, shape_length, shape_area, Shape) %>% 
  rename(geoid = id)

ice_facilities_raw_df <- read_csv(here('data/icefacilities.csv'))  %>% 
  clean_names()

## Filter the ones without GEOID, need to manually work on it
ice_facilities_df <- ice_facilities_raw_df %>% 
    filter(!is.na(geoid)) %>% 
  select(name, type_detailed, category, fy24_adp, geoid, longitude, latitude)

## Merging the data of CDC and ICE facilities with common GEOID, lost of lot of data, need manual work.
detention_df <- ejscreen_sf %>%
  inner_join(ice_facilities_df, by = "geoid") %>% 
  drop_na()



summary(detention_df)
names(detention_df)



```

```{r}
st_crs(detention_df) <- st_crs("+proj=longlat +datum=WGS84")
detention_sf <- st_as_sf(detention_df
                         , coords = c("LONGITUDE", "LATITUDE")) %>% 
 select(-geoid)

library(leaflet)
library(leaflet.extras)

# Create leaflet map
leaflet() %>%
  addPolygons(data = ejscreen_sf,
              fillColor = ~colorQuantile("viridis", p_cancer)(p_cancer),
              fillOpacity = 0.7,
              color = "#BDBDBD",
              weight = 1,
              label = ~paste("Percentile of Cancer:", p_cancer)) %>%
  addLegend("bottomleft", 
            pal = colorQuantile("viridis", p_cancer),
            values = ~p_cancer,
            title = "Percentile of Cancer",
            opacity = 0.7) %>%
  setView(lng = -98.58333, lat = 39.83333, zoom = 4) 

```


```{r}


st_crs(detention_df) <- st_crs("+proj=longlat +datum=WGS84")
detention_sf <- st_as_sf(detention_df, coords = c("LONGITUDE", "LATITUDE")) %>% 
  select(-geoid)

color_palette <- c("#EFF3FF", "#BDD7E7", "#6BAED6", "#2171B5")

# Create a leaflet map with census tracts colored by p_cancer
map <- leaflet(ejscreen_sf) %>%
  addPolygons(fillColor = ~colorQuantile(color_palette, p_cancer)(p_cancer),
              fillOpacity = 0.7,
              color = "#BDBDBD",
              weight = 1,
              label = ~paste("Environmental Justice Index:", p_cancer)) %>%
  addLegend("bottomleft", 
            colors = color_palette,
            labels = c("Low", "", "", "High"),
            title = "p_cancer",
            opacity = 0.7) 

map_detention_centers <- map %>%
  addCircleMarkers(data = detention_sf,
                   lng = ~LONGITUDE,
                   lat = ~LATITUDE,
                   radius = 4,
                   color = "black",
                   fillColor = "white",
                   fillOpacity = 1,
                   popup = ~as.character(name))

map_combined <- map_detention_centers %>%
  addLayersControl(
    baseGroups = c("Census Tracts (p_cancer)", "Detention Centers"),
    options = layersControlOptions(collapsed = FALSE)
  )

map_combined


```

```{r}
 
detention_data <- read_csv(here("iceavailable.csv")) %>% 
  clean_names()

anova_model <- aov(rpl_eji ~ name, data = detention_data)
summary(anova_model)

ggplot(detention_data) +
  geom_boxplot(aes(y = rpl_eji)) +
  labs(title = "Distribution of Environmental Justice Index by Detention Center") +
  theme_minimal()


ggplot(detention_data) +
  geom_boxplot(aes(x = name, y = epl_npl)) +
  labs(title = "Distribution of Environmental Justice Index by Detention Center") +
  theme_minimal()

summary(detention_data)

```

```{r}

## Cleaning the entire raw dataset
ice_facilities_raw_df <- read_csv(here('data/icefacilities.csv')) %>% 
  clean_names()
 

## source: https://www.ice.gov/doclib/facilityInspections/dedicatedNonDedicatedFacilityList.xlsx
 
## Dropping columns for now not deemed very relevant to the analysis
 
## names(ice_facilities_raw_df) for selection

ice_facilities_df <-  ice_facilities_raw_df %>% 
  select(name, address, city, state, zip,
         type_detailed, fy24_adp, over_under_72_status,
         medical_personal, category) %>% 
         rename(facility_name = name)

ice_facilities_census <- ice_facilities_raw_df



ice_facilities_merge <- left_join(ice_facilities_df, addon_data_ice %>% 
                        select(address, facility_operator), by = "address") 
                      

ice_facilities_merge <- ice_facilities_merge[1:143, ]



na_count <- sum(is.na(ice_facilities_merge$facility_operator))
 




```
